// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
    using Castle.ActiveRecord;
	using Castle.ActiveRecord.Queries;
    
    
    [ActiveRecord("ApplySheetHead")]
    public class ApplySheetHead : ActiveRecordBase
    {
        
        private int _applySheetHeadPk;
        
        private string _applySheetNo;
        
        private string _applyTypeCode;
        
        private System.DateTime _applyDate;
        
        private string _applyDeptClassCode;
        
        private string _applyDeptCode;
        
        private string _applyPersonCode;
        
        private string _applyProcessCode;
        
        private int _isCheckInCompany;
        
        private string _currentCheckRole;
        
        private string _applyPersonName;
        
        private string _applyMakerCode;
        
        private string _applyMakerName;
        
        private int _checkFlowInCompanyHeadPk;

		private int _isKeeping;

		private int _checkSetp;

		private string _deliveryDate;
    
		private System.DateTime _submitDate;
    
		private int _isOverBudget;

		private int _isExpense;
    
		private System.DateTime _expenseDate;

		private string _reasonForAsset;
    
		private string _effect;

		private System.Decimal _overMoney;
        
        [PrimaryKey(PrimaryKeyType.Native, "ApplySheetHead_Pk")]
        public int ApplySheetHeadPk
        {
            get
            {
                return this._applySheetHeadPk;
            }
            set
            {
                this._applySheetHeadPk = value;
            }
        }
        
        [Property()]
        public string ApplySheetNo
        {
            get
            {
                return this._applySheetNo;
            }
            set
            {
                this._applySheetNo = value;
            }
        }
        
        [Property()]
        public string ApplyTypeCode
        {
            get
            {
                return this._applyTypeCode;
            }
            set
            {
                this._applyTypeCode = value;
            }
        }
        
        [Property()]
        public System.DateTime ApplyDate
        {
            get
            {
                return this._applyDate;
            }
            set
            {
                this._applyDate = value;
            }
        }
        
        [Property()]
        public string ApplyDeptClassCode
        {
            get
            {
                return this._applyDeptClassCode;
            }
            set
            {
                this._applyDeptClassCode = value;
            }
        }
        
        [Property()]
        public string ApplyDeptCode
        {
            get
            {
                return this._applyDeptCode;
            }
            set
            {
                this._applyDeptCode = value;
            }
        }
        
        [Property()]
        public string ApplyPersonCode
        {
            get
            {
                return this._applyPersonCode;
            }
            set
            {
                this._applyPersonCode = value;
            }
        }
        
        [Property()]
        public string ApplyProcessCode
        {
            get
            {
                return this._applyProcessCode;
            }
            set
            {
                this._applyProcessCode = value;
            }
        }
        
        [Property()]
        public int IsCheckInCompany
        {
            get
            {
                return this._isCheckInCompany;
            }
            set
            {
                this._isCheckInCompany = value;
            }
        }
        
        [Property()]
        public string CurrentCheckRole
        {
            get
            {
                return this._currentCheckRole;
            }
            set
            {
                this._currentCheckRole = value;
            }
        }
        
        [Property()]
        public string ApplyPersonName
        {
            get
            {
                return this._applyPersonName;
            }
            set
            {
                this._applyPersonName = value;
            }
        }
        
        [Property()]
        public string ApplyMakerCode
        {
            get
            {
                return this._applyMakerCode;
            }
            set
            {
                this._applyMakerCode = value;
            }
        }
        
        [Property()]
        public string ApplyMakerName
        {
            get
            {
                return this._applyMakerName;
            }
            set
            {
                this._applyMakerName = value;
            }
        }
        
        [Property(Column="CheckFlowInCompany_Head_pk")]
        public int CheckFlowInCompanyHeadPk
        {
            get
            {
                return this._checkFlowInCompanyHeadPk;
            }
            set
            {
                this._checkFlowInCompanyHeadPk = value;
            }
        }

		[Property()]
		public int IsKeeping
		{
			get
			{
				return this._isKeeping;
			}
			set
			{
				this._isKeeping = value;
			}
		}

		[Property()]
		public int CheckSetp
		{
			get
			{
				return this._checkSetp;
			}
			set
			{
				this._checkSetp = value;
			}
		}


		[Property()]
		public string DeliveryDate
		{
			get
			{
				return this._deliveryDate;
			}
			set
			{
				this._deliveryDate = value;
			}
		}
    
		[Property()]
		public System.DateTime SubmitDate
		{
			get
			{
				return this._submitDate;
			}
			set
			{
				this._submitDate = value;
			}
		}
    
		[Property()]
		public int IsOverBudget
		{
			get
			{
				return this._isOverBudget;
			}
			set
			{
				this._isOverBudget = value;
			}
		}

		[Property()]
		public decimal OverMoney
		{
			get
			{
				return this._overMoney;
			}
			set
			{
				this._overMoney = value;
			}
		}

		[Property()]
		public int IsExpense
		{
			get
			{
				return this._isExpense;
			}
			set
			{
				this._isExpense = value;
			}
		}
    
		[Property()]
		public System.DateTime ExpenseDate
		{
			get
			{
				return this._expenseDate;
			}
			set
			{
				this._expenseDate = value;
			}
		}

		[Property()]
		public string ReasonForAsset
		{
			get
			{
				return this._reasonForAsset;
			}
			set
			{
				this._reasonForAsset = value;
			}
		}
    
		[Property()]
		public string Effect
		{
			get
			{
				return this._effect;
			}
			set
			{
				this._effect = value;
			}
		}

    
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(ApplySheetHead));
        }
        
        public static ApplySheetHead[] FindAll()
        {
            return ((ApplySheetHead[])(ActiveRecordBase.FindAll(typeof(ApplySheetHead))));
        }
        
        public static ApplySheetHead Find(int ApplySheetHeadPk)
        {
            return ((ApplySheetHead)(ActiveRecordBase.FindByPrimaryKey(typeof(ApplySheetHead), ApplySheetHeadPk,false)));
        }

		public static ApplySheetHead  SelectApplySheetHeadPk(string applySheetNo)
		{
			SimpleQuery  query=new SimpleQuery(typeof(ApplySheetHead),@"from ApplySheetHead o where o.ApplySheetNo=?",applySheetNo);
			ApplySheetHead[] applySheetHeads =(ApplySheetHead[])ExecuteQuery(query);
			if(applySheetHeads!=null && applySheetHeads.Length>0)
			{
				return applySheetHeads[0];
			}
			else
			{
				return null;
			}
		}
    }
}
