// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
    using Castle.ActiveRecord;
	using Castle.ActiveRecord.Queries;    
    
    [ActiveRecord("ApplySheetBody_Purchase")]
    public class ApplySheetBodyPurchase : ActiveRecordBase
    {
        
        private int _applySheetBodyPurchasePk;
        
        private int _applySheetHeadPk;
        
        private string _inventoryClassCode;
        
        private string _inventoryCode;
        
        private string _inventoryName;
        
        private string _unit;
        
        private System.Decimal _number;
        
        private string _currTypeCode;
        
        private System.Decimal _exchangeRate;
        
        private System.Decimal _originalcurrPrice;
        
        private System.Decimal _rMBPrice;
        
        private System.Decimal _money;
        
        private string _memo;
        
        private string _iNVTYPE;
		
		private string _inventoryClassFirstLevel;

		private int _isOrder;
    
		private System.DateTime _orderDate;
    
		private string _orderNo;
        
        [PrimaryKey(PrimaryKeyType.Native, "ApplySheetBody_Purchase_pk")]
        public int ApplySheetBodyPurchasePk
        {
            get
            {
                return this._applySheetBodyPurchasePk;
            }
            set
            {
                this._applySheetBodyPurchasePk = value;
            }
        }
        
        [Property(Column="ApplySheetHead_Pk")]
        public int ApplySheetHeadPk
        {
            get
            {
                return this._applySheetHeadPk;
            }
            set
            {
                this._applySheetHeadPk = value;
            }
        }
        
        [Property()]
        public string InventoryClassCode
        {
            get
            {
                return this._inventoryClassCode;
            }
            set
            {
                this._inventoryClassCode = value;
            }
        }
        
        [Property()]
        public string InventoryCode
        {
            get
            {
                return this._inventoryCode;
            }
            set
            {
                this._inventoryCode = value;
            }
        }
        
        [Property()]
        public string InventoryName
        {
            get
            {
                return this._inventoryName;
            }
            set
            {
                this._inventoryName = value;
            }
        }
        
        [Property()]
        public string Unit
        {
            get
            {
                return this._unit;
            }
            set
            {
                this._unit = value;
            }
        }
        
        [Property()]
        public System.Decimal Number
        {
            get
            {
                return this._number;
            }
            set
            {
                this._number = value;
            }
        }
        
        [Property()]
        public string CurrTypeCode
        {
            get
            {
                return this._currTypeCode;
            }
            set
            {
                this._currTypeCode = value;
            }
        }
        
        [Property()]
        public System.Decimal ExchangeRate
        {
            get
            {
                return this._exchangeRate;
            }
            set
            {
                this._exchangeRate = value;
            }
        }
        
        [Property()]
        public System.Decimal OriginalcurrPrice
        {
            get
            {
                return this._originalcurrPrice;
            }
            set
            {
                this._originalcurrPrice = value;
            }
        }
        
        [Property()]
        public System.Decimal RMBPrice
        {
            get
            {
                return this._rMBPrice;
            }
            set
            {
                this._rMBPrice = value;
            }
        }
        
        [Property()]
        public System.Decimal Money
        {
            get
            {
                return this._money;
            }
            set
            {
                this._money = value;
            }
        }
        
        [Property()]
        public string Memo
        {
            get
            {
                return this._memo;
            }
            set
            {
                this._memo = value;
            }
        }
        
        [Property()]
        public string INVTYPE
        {
            get
            {
                return this._iNVTYPE;
            }
            set
            {
                this._iNVTYPE = value;
            }
        }

		[Property()]
		public string InventoryClassFirstLevel
		{
			get
			{
				return this._inventoryClassFirstLevel;
			}
			set
			{
				this._inventoryClassFirstLevel = value;
			}
		}

		[Property()]
		public int IsOrder
		{
			get
			{
				return this._isOrder;
			}
			set
			{
				this._isOrder = value;
			}
		}
    
		[Property()]
		public System.DateTime OrderDate
		{
			get
			{
				return this._orderDate;
			}
			set
			{
				this._orderDate = value;
			}
		}
    
		[Property()]
		public string OrderNo
		{
			get
			{
				return this._orderNo;
			}
			set
			{
				this._orderNo = value;
			}
		}
    

        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(ApplySheetBodyPurchase));
        }
        
        public static ApplySheetBodyPurchase[] FindAll()
        {
            return ((ApplySheetBodyPurchase[])(ActiveRecordBase.FindAll(typeof(ApplySheetBodyPurchase))));
        }
        
        public static ApplySheetBodyPurchase Find(int ApplySheetBodyPurchasePk)
        {
            return ((ApplySheetBodyPurchase)(ActiveRecordBase.FindByPrimaryKey(typeof(ApplySheetBodyPurchase), ApplySheetBodyPurchasePk,false)));
        }

		public static ApplySheetBodyPurchase[] FindByApplyHeadPk(int ApplyHeadPk)
		{
			SimpleQuery query=new SimpleQuery(typeof(ApplySheetBodyPurchase),@"from ApplySheetBodyPurchase o where  o.ApplySheetHeadPk=?",ApplyHeadPk);
			return (ApplySheetBodyPurchase[])ExecuteQuery(query);
		}
    }
}
