// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
    using Castle.ActiveRecord;
	using Castle.ActiveRecord.Queries;
    
    
    [ActiveRecord("Asset_FinallyPriceCheck_Body")]
    public class AssetFinallyPriceCheckBody : ActiveRecordBase
    {
        
    
		private int _id;

		private int _finallyPriceCheckId ; 
    
		private int _assetApplySheetBodyId;
    
		private string _subjectName;
    
		private string _inventoryName;
    
		private string _offer;
    
		private string _article;
    
		private string _remark;
    
		private int _baseUnitId;
    
		private int _number;
    
		private System.Decimal _originalcurrPrice;
    
		private string _currTypeCode;
    
		private System.Decimal _exchangeRate;
    
		private System.Decimal _finallyPrice;
    
		private System.Decimal _checkMoney;
    
		private int _isArrived;
    
		private string _arriveSigner;
    
		private string _arriveDatetime;
    
		private int _isInStore;
    
		private string _inStoreSigner;
    
		private string _inStoreDatetime;
    
		private int _isPayFor;
    
		private System.Decimal _reallyPayMoney;
    
		private string _payForSigner;
    
		private string _payForDatetime;
    
		private string _payForRemark;
    
		private int _earnest;
    
		private string _earnestSigner;
    
		private string _earnestDatetime;
    
		private string _earnestRemark;
    
        
        [PrimaryKey(PrimaryKeyType.Native)]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        [Property(Column="FinallyPriceCheck_Id")]
        public int FinallyPriceCheckId
        {
            get
            {
                return this._finallyPriceCheckId;
            }
            set
            {
                this._finallyPriceCheckId = value;
            }
        }

		[Property(Column="Asset_ApplySheet_Body_Id")]
		public int AssetApplySheetBodyId
		{
			get
			{
				return this._assetApplySheetBodyId;
			}
			set
			{
				this._assetApplySheetBodyId = value;
			}
		}

		[Property()]
		public string SubjectName
		{
			get
			{
				return this._subjectName;
			}
			set
			{
				this._subjectName = value;
			}
		}
    
		[Property()]
		public string InventoryName
		{
			get
			{
				return this._inventoryName;
			}
			set
			{
				this._inventoryName = value;
			}
		}
    
		[Property()]
		public string Offer
		{
			get
			{
				return this._offer;
			}
			set
			{
				this._offer = value;
			}
		}
    
		[Property()]
		public string Article
		{
			get
			{
				return this._article;
			}
			set
			{
				this._article = value;
			}
		}
    
		[Property()]
		public string Remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				this._remark = value;
			}
		}
    
		[Property(Column="Base_Unit_id")]
		public int BaseUnitId
		{
			get
			{
				return this._baseUnitId;
			}
			set
			{
				this._baseUnitId = value;
			}
		}
    
		[Property()]
		public int Number
		{
			get
			{
				return this._number;
			}
			set
			{
				this._number = value;
			}
		}
    
		[Property()]
		public System.Decimal OriginalcurrPrice
		{
			get
			{
				return this._originalcurrPrice;
			}
			set
			{
				this._originalcurrPrice = value;
			}
		}
    
		[Property()]
		public string CurrTypeCode
		{
			get
			{
				return this._currTypeCode;
			}
			set
			{
				this._currTypeCode = value;
			}
		}
    
		[Property()]
		public System.Decimal ExchangeRate
		{
			get
			{
				return this._exchangeRate;
			}
			set
			{
				this._exchangeRate = value;
			}
		}
    
		[Property()]
		public System.Decimal FinallyPrice
		{
			get
			{
				return this._finallyPrice;
			}
			set
			{
				this._finallyPrice = value;
			}
		}
    
		[Property()]
		public System.Decimal CheckMoney
		{
			get
			{
				return this._checkMoney;
			}
			set
			{
				this._checkMoney = value;
			}
		}
    
		[Property()]
		public int IsArrived
		{
			get
			{
				return this._isArrived;
			}
			set
			{
				this._isArrived = value;
			}
		}
    
		[Property()]
		public string ArriveSigner
		{
			get
			{
				return this._arriveSigner;
			}
			set
			{
				this._arriveSigner = value;
			}
		}
    
		[Property()]
		public string ArriveDatetime
		{
			get
			{
				return this._arriveDatetime;
			}
			set
			{
				this._arriveDatetime = value;
			}
		}
    
		[Property()]
		public int IsInStore
		{
			get
			{
				return this._isInStore;
			}
			set
			{
				this._isInStore = value;
			}
		}
    
		[Property()]
		public string InStoreSigner
		{
			get
			{
				return this._inStoreSigner;
			}
			set
			{
				this._inStoreSigner = value;
			}
		}
    
		[Property()]
		public string InStoreDatetime
		{
			get
			{
				return this._inStoreDatetime;
			}
			set
			{
				this._inStoreDatetime = value;
			}
		}
    
		[Property()]
		public int IsPayFor
		{
			get
			{
				return this._isPayFor;
			}
			set
			{
				this._isPayFor = value;
			}
		}
    
		[Property()]
		public System.Decimal ReallyPayMoney
		{
			get
			{
				return this._reallyPayMoney;
			}
			set
			{
				this._reallyPayMoney = value;
			}
		}
    
		[Property()]
		public string PayForSigner
		{
			get
			{
				return this._payForSigner;
			}
			set
			{
				this._payForSigner = value;
			}
		}
    
		[Property()]
		public string PayForDatetime
		{
			get
			{
				return this._payForDatetime;
			}
			set
			{
				this._payForDatetime = value;
			}
		}
    
		[Property()]
		public string PayForRemark
		{
			get
			{
				return this._payForRemark;
			}
			set
			{
				this._payForRemark = value;
			}
		}
    
		[Property()]
		public int Earnest
		{
			get
			{
				return this._earnest;
			}
			set
			{
				this._earnest = value;
			}
		}
    
		[Property()]
		public string EarnestSigner
		{
			get
			{
				return this._earnestSigner;
			}
			set
			{
				this._earnestSigner = value;
			}
		}
    
		[Property()]
		public string EarnestDatetime
		{
			get
			{
				return this._earnestDatetime;
			}
			set
			{
				this._earnestDatetime = value;
			}
		}
    
		[Property()]
		public string EarnestRemark
		{
			get
			{
				return this._earnestRemark;
			}
			set
			{
				this._earnestRemark = value;
			}
		}

        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(AssetFinallyPriceCheckBody));
        }
        
        public static AssetFinallyPriceCheckBody[] FindAll()
        {
            return ((AssetFinallyPriceCheckBody[])(ActiveRecordBase.FindAll(typeof(AssetFinallyPriceCheckBody))));
        }
        
        public static AssetFinallyPriceCheckBody Find(int Id)
        {
            return ((AssetFinallyPriceCheckBody)(ActiveRecordBase.FindByPrimaryKey(typeof(AssetFinallyPriceCheckBody), Id,false)));
        }

		//根据 年份，预算部门，项目找对应预算。
		public static AssetFinallyPriceCheckBody[] FindByCheckApplyHeadKey(int CheckApplyHeadKey)
		{
			SimpleQuery query=new SimpleQuery(typeof(AssetFinallyPriceCheckBody),@"from AssetFinallyPriceCheckBody o where o.FinallyPriceCheckId= ? ",CheckApplyHeadKey);
			return (AssetFinallyPriceCheckBody[])ExecuteQuery(query); 
			
		}
    }
}
