// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
    using Castle.ActiveRecord;
	using Castle.ActiveRecord.Queries;  
    
    [ActiveRecord("Asset_ApplySheet_Budget")]
    public class AssetApplySheetBudget : ActiveRecordBase
    {
        
        private int _id;
        
        private int _applySheetHeadPk;
        
        private string _itemName;
        
        private System.Decimal _sheetRmbMoney;
        
        private System.Decimal _sumCheckMoney;
        
        private System.Decimal _allowOutMoney;
        
        private int _submitType;
        
        [PrimaryKey(PrimaryKeyType.Native)]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        [Property(Column="ApplySheetHead_Pk")]
        public int ApplySheetHeadPk
        {
            get
            {
                return this._applySheetHeadPk;
            }
            set
            {
                this._applySheetHeadPk = value;
            }
        }
        
        [Property()]
        public string ItemName
        {
            get
            {
                return this._itemName;
            }
            set
            {
                this._itemName = value;
            }
        }
        
        [Property()]
        public System.Decimal SheetRmbMoney
        {
            get
            {
                return this._sheetRmbMoney;
            }
            set
            {
                this._sheetRmbMoney = value;
            }
        }
        
        [Property()]
        public System.Decimal SumCheckMoney
        {
            get
            {
                return this._sumCheckMoney;
            }
            set
            {
                this._sumCheckMoney = value;
            }
        }
        
        [Property()]
        public System.Decimal AllowOutMoney
        {
            get
            {
                return this._allowOutMoney;
            }
            set
            {
                this._allowOutMoney = value;
            }
        }
        
        [Property()]
        public int SubmitType
        {
            get
            {
                return this._submitType;
            }
            set
            {
                this._submitType = value;
            }
        }
        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(AssetApplySheetBudget));
        }
        
        public static AssetApplySheetBudget[] FindAll()
        {
            return ((AssetApplySheetBudget[])(ActiveRecordBase.FindAll(typeof(AssetApplySheetBudget))));
        }
        
        public static AssetApplySheetBudget Find(int Id)
        {
            return ((AssetApplySheetBudget)(ActiveRecordBase.FindByPrimaryKey(typeof(AssetApplySheetBudget), Id,false)));
        }

//		public static AssetApplySheetBudget FindByApplyHeadPk(int ApplySheetHeadPk)
//		{
//			return ((AssetApplySheetBudget)(ActiveRecordBase.FindByPrimaryKey(typeof(AssetApplySheetBudget), ApplySheetHeadPk,false)));
//		}

		//根据 年份，预算部门，项目找对应预算。
		public static AssetApplySheetBudget FindByApplyHeadPk(int ApplySheetHeadPk)
		{
			SimpleQuery query=new SimpleQuery(typeof(AssetApplySheetBudget),@"from AssetApplySheetBudget o where o.ApplySheetHeadPk= ?  ",ApplySheetHeadPk);
			AssetApplySheetBudget []budGet = (AssetApplySheetBudget[])ExecuteQuery(query); 
			if(budGet!=null && budGet.Length>0)
			{
				return budGet[0];
			}
			else
			{
				return null;
			}
		}


    }
}
