// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("Base_InvClass")]
    public class BaseInvClas : ActiveRecordBase
    {
        
        private string _invClassPk;
        
        private string _invClassCode;
        
        private string _invClassName;
        
        [PrimaryKey(PrimaryKeyType.Native, "InvClass_pk")]
        public string InvClassPk
        {
            get
            {
                return this._invClassPk;
            }
            set
            {
                this._invClassPk = value;
            }
        }
        
        [Property()]
        public string InvClassCode
        {
            get
            {
                return this._invClassCode;
            }
            set
            {
                this._invClassCode = value;
            }
        }
        
        [Property()]
        public string InvClassName
        {
            get
            {
                return this._invClassName;
            }
            set
            {
                this._invClassName = value;
            }
        }
        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(BaseInvClas));
        }
        
        public static BaseInvClas[] FindAll()
        {
            return ((BaseInvClas[])(ActiveRecordBase.FindAll(typeof(BaseInvClas))));
        }
        
        public static BaseInvClas Find(string InvClassPk)
        {
            return ((BaseInvClas)(ActiveRecordBase.FindByPrimaryKey(typeof(BaseInvClas), InvClassPk,false)));
        }
    }
}
