// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
    using Castle.ActiveRecord;
	using Castle.ActiveRecord.Queries;
    
    [ActiveRecord("Base_currencyType")]
    public class BasecurrencyType : ActiveRecordBase
    {
        
        private string _currTypeCode;
        
        private string _currTypeName;
        
        private System.Decimal _exchangeRate;

		private int _iYear;

		private int _iMonth ;
        
        [PrimaryKey(PrimaryKeyType.Native)]
        public string CurrTypeCode
        {
            get
            {
                return this._currTypeCode;
            }
            set
            {
                this._currTypeCode = value;
            }
        }
        
        [Property()]
        public string CurrTypeName
        {
            get
            {
                return this._currTypeName;
            }
            set
            {
                this._currTypeName = value;
            }
        }
        
        [Property()]
        public System.Decimal ExchangeRate
        {
            get
            {
                return this._exchangeRate;
            }
            set
            {
                this._exchangeRate = value;
            }
        }

		[Property()]
		public int Iyear
		{
			get
			{
				return this._iYear;
			}
			set
			{
				this._iYear = value;
			}
		}


		[Property()]
		public int Imonth
		{
			get
			{
				return this._iMonth;
			}
			set
			{
				this._iMonth = value;
			}
		}
        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(BasecurrencyType));
        }
        
        public static BasecurrencyType[] FindAll()
        {
            return ((BasecurrencyType[])(ActiveRecordBase.FindAll(typeof(BasecurrencyType))));
        }
        
        public static BasecurrencyType Find(string CurrTypeCode)
        {
            return ((BasecurrencyType)(ActiveRecordBase.FindByPrimaryKey(typeof(BasecurrencyType), CurrTypeCode,false)));
        }

		public static BasecurrencyType FindByYearAndMonth(string CurrTypeCode,int iYear ,int iMonth)
		{
			//查找最后一个审批人
			SimpleQuery query =new SimpleQuery(typeof(BasecurrencyType),@"from BasecurrencyType o where o.CurrTypeCode=? and  o.Iyear=? and o.Imonth=?  ",CurrTypeCode,iYear,iMonth);
			BasecurrencyType[] BasecurrencyTypes=(BasecurrencyType[])ExecuteQuery(query);
			if(BasecurrencyTypes!=null && BasecurrencyTypes.Length>0)
			{
				return BasecurrencyTypes[0];
			}
			else
			{
				return null;
			}
		}

    }
}
