// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("Base_Email")]
    public class BaseEmail : ActiveRecordBase
    {
        
        private string _personCode;
        
        private string _email;
        
        private string _nickName;
		//ÐÂÔöÐÕÃû
        private string _name;

		private int _IsAccept;

		[Property()]
		public string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}


        [PrimaryKey(PrimaryKeyType.Native)]
        public string PersonCode
        {
            get
            {
                return this._personCode;
            }
            set
            {
                this._personCode = value;
            }
        }
        
        [Property()]
        public string Email
        {
            get
            {
                return this._email;
            }
            set
            {
                this._email = value;
            }
        }
        
        [Property()]
        public string NickName
        {
            get
            {
                return this._nickName;
            }
            set
            {
                this._nickName = value;
            }
        }

		
		[Property()]
		public int IsAccept
		{
			get
			{
				return this._IsAccept;
			}
			set
			{
				this._IsAccept = value;
			}
		}
        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(BaseEmail));
        }
        
        public static BaseEmail[] FindAll()
        {
            return ((BaseEmail[])(ActiveRecordBase.FindAll(typeof(BaseEmail))));
        }
        
        public static BaseEmail Find(string PersonCode)
        {
            return ((BaseEmail)(ActiveRecordBase.FindByPrimaryKey(typeof(BaseEmail), PersonCode,false)));
        }
    }
}
