// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("Bl_Personnel_All")]
    public class BlPersonnelAll : ActiveRecordBase
    {
        
        private string _nameno;
        
        private string _name;
        
        private string _sex;
        
        private string _deptcode;
        
        private string _deptname;
        
        private string _zhiwu;
        
        private string _zj;
        
        private string _gangwei;
        
        private string _joindate;
        
        private string _resigndate;
        
        private string _bmbh1;
        
        [PrimaryKey(PrimaryKeyType.Native)]
        public string Nameno
        {
            get
            {
                return this._nameno;
            }
            set
            {
                this._nameno = value;
            }
        }
        
        [Property()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [Property()]
        public string Sex
        {
            get
            {
                return this._sex;
            }
            set
            {
                this._sex = value;
            }
        }
        
        [Property()]
        public string Deptcode
        {
            get
            {
                return this._deptcode;
            }
            set
            {
                this._deptcode = value;
            }
        }
        
        [Property()]
        public string Deptname
        {
            get
            {
                return this._deptname;
            }
            set
            {
                this._deptname = value;
            }
        }
        
        [Property()]
        public string Zhiwu
        {
            get
            {
                return this._zhiwu;
            }
            set
            {
                this._zhiwu = value;
            }
        }
        
        [Property()]
        public string Zj
        {
            get
            {
                return this._zj;
            }
            set
            {
                this._zj = value;
            }
        }
        
        [Property()]
        public string Gangwei
        {
            get
            {
                return this._gangwei;
            }
            set
            {
                this._gangwei = value;
            }
        }
        
        [Property()]
        public string Joindate
        {
            get
            {
                return this._joindate;
            }
            set
            {
                this._joindate = value;
            }
        }
        
        [Property()]
        public string Resigndate
        {
            get
            {
                return this._resigndate;
            }
            set
            {
                this._resigndate = value;
            }
        }
        
        [Property()]
        public string Bmbh1
        {
            get
            {
                return this._bmbh1;
            }
            set
            {
                this._bmbh1 = value;
            }
        }
        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(BlPersonnelAll));
        }
        
        public static BlPersonnelAll[] FindAll()
        {
            return ((BlPersonnelAll[])(ActiveRecordBase.FindAll(typeof(BlPersonnelAll))));
        }
        
        public static BlPersonnelAll Find(string Nameno)
        {
            return ((BlPersonnelAll)(ActiveRecordBase.FindByPrimaryKey(typeof(BlPersonnelAll), Nameno,false)));
        }
    }
}
