// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
    using Castle.ActiveRecord;
	using Castle.ActiveRecord.Queries;
    
    
    [ActiveRecord("CheckPersonInRole")]
    public class CheckPersonInRole : ActiveRecordBase
    {
        
        private int _personInRolePk;
        
        private string _checkRoleCode;
        
        private string _personCode;
        
        [PrimaryKey(PrimaryKeyType.Native, "PersonInRole_pk")]
        public int PersonInRolePk
        {
            get
            {
                return this._personInRolePk;
            }
            set
            {
                this._personInRolePk = value;
            }
        }
        
        [Property()]
        public string CheckRoleCode
        {
            get
            {
                return this._checkRoleCode;
            }
            set
            {
                this._checkRoleCode = value;
            }
        }
        
        [Property()]
        public string PersonCode
        {
            get
            {
                return this._personCode;
            }
            set
            {
                this._personCode = value;
            }
        }
        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(CheckPersonInRole));
        }
        
        public static CheckPersonInRole[] FindAll()
        {
            return ((CheckPersonInRole[])(ActiveRecordBase.FindAll(typeof(CheckPersonInRole))));
        }
        
        public static CheckPersonInRole Find(int PersonInRolePk)
        {
            return ((CheckPersonInRole)(ActiveRecordBase.FindByPrimaryKey(typeof(CheckPersonInRole), PersonInRolePk,false)));
        }

		public static CheckPersonInRole[] FindByUserCode(string UserCode)
		{
			//根据用户工号查询
			SimpleQuery query=new SimpleQuery(typeof(CheckPersonInRole),@"from CheckPersonInRole o where o.PersonCode=?",UserCode);
			CheckPersonInRole[] checkPersonInRole=(CheckPersonInRole[])ExecuteQuery(query);
			return checkPersonInRole;
		}

		public static CheckPersonInRole[] FindByRole(string Role)
		{
			//根据角色查询
			SimpleQuery query=new SimpleQuery(typeof(CheckPersonInRole),@"from CheckPersonInRole o where o.CheckRoleCode=? ",Role);
			CheckPersonInRole[] checkPersonInRole=(CheckPersonInRole[])ExecuteQuery(query);
			return checkPersonInRole;
		}

    }
}
