// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
    using Castle.ActiveRecord;
    using Castle.ActiveRecord.Queries;
    
    [ActiveRecord("OrderSheet")]
    public class OrderSheet : ActiveRecordBase
    {
        
        private int _id;
        
        private string _orderNo;
        
        private System.DateTime _orderDate;
        
        private int _isKeep;

		private string _makerCode;
    
		private string _makerName;
        
        [PrimaryKey(PrimaryKeyType.Native)]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        [Property()]
        public string OrderNo
        {
            get
            {
                return this._orderNo;
            }
            set
            {
                this._orderNo = value;
            }
        }
        
        [Property()]
        public System.DateTime OrderDate
        {
            get
            {
                return this._orderDate;
            }
            set
            {
                this._orderDate = value;
            }
        }
        
        [Property()]
        public int IsKeep
        {
            get
            {
                return this._isKeep;
            }
            set
            {
                this._isKeep = value;
            }
        }

		[Property()]
		public string MakerCode
		{
			get
			{
				return this._makerCode;
			}
			set
			{
				this._makerCode = value;
			}
		}
    
		[Property()]
		public string MakerName
		{
			get
			{
				return this._makerName;
			}
			set
			{
				this._makerName = value;
			}
		}
        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(OrderSheet));
        }
        
        public static OrderSheet[] FindAll()
        {
            return ((OrderSheet[])(ActiveRecordBase.FindAll(typeof(OrderSheet))));
        }
        
        public static OrderSheet Find(int Id)
        {
            return ((OrderSheet)(ActiveRecordBase.FindByPrimaryKey(typeof(OrderSheet), Id,false)));
        }

		public static OrderSheet FindByOrderNo(string OrderNo)
		{
			SimpleQuery query = new SimpleQuery(typeof(OrderSheet),"from  OrderSheet o where o.OrderNo = ?",OrderNo);
			OrderSheet[] orderSheet = (OrderSheet[])ExecuteQuery(query);
			if(orderSheet!=null && orderSheet.Length>0)
			{
				return orderSheet[0];
			}
			else
			{
				return null;
			}
		}
    }
}
