// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("RealMoneyAlterSheet")]
    public class RealMoneyAlterSheet : ActiveRecordBase
    {
        
        private int _id;
        
        private int _alteredSheetHeadPk;
        
        private System.DateTime _sheetDate;
        
        private string _markerCode;
        
        private string _firstSubjectCode;
        
        private string _subjectCode;
        
        private string _budgetDept;
        
        private int _alterYear;
        
        private int _alterMonth;
        
        private System.Decimal _alterMoney;
        
        private string _memo;
        
        private int _isSubmit;
        
        [PrimaryKey(PrimaryKeyType.Native)]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        [Property(Column="AlteredSheetHead_pk")]
        public int AlteredSheetHeadPk
        {
            get
            {
                return this._alteredSheetHeadPk;
            }
            set
            {
                this._alteredSheetHeadPk = value;
            }
        }
        
        [Property()]
        public System.DateTime SheetDate
        {
            get
            {
                return this._sheetDate;
            }
            set
            {
                this._sheetDate = value;
            }
        }
        
        [Property()]
        public string MarkerCode
        {
            get
            {
                return this._markerCode;
            }
            set
            {
                this._markerCode = value;
            }
        }
        
        [Property()]
        public string FirstSubjectCode
        {
            get
            {
                return this._firstSubjectCode;
            }
            set
            {
                this._firstSubjectCode = value;
            }
        }
        
        [Property()]
        public string SubjectCode
        {
            get
            {
                return this._subjectCode;
            }
            set
            {
                this._subjectCode = value;
            }
        }
        
        [Property()]
        public string BudgetDept
        {
            get
            {
                return this._budgetDept;
            }
            set
            {
                this._budgetDept = value;
            }
        }
        
        [Property()]
        public int AlterYear
        {
            get
            {
                return this._alterYear;
            }
            set
            {
                this._alterYear = value;
            }
        }
        
        [Property()]
        public int AlterMonth
        {
            get
            {
                return this._alterMonth;
            }
            set
            {
                this._alterMonth = value;
            }
        }
        
        [Property()]
        public System.Decimal AlterMoney
        {
            get
            {
                return this._alterMoney;
            }
            set
            {
                this._alterMoney = value;
            }
        }
        
        [Property()]
        public string Memo
        {
            get
            {
                return this._memo;
            }
            set
            {
                this._memo = value;
            }
        }
        
        [Property()]
        public int IsSubmit
        {
            get
            {
                return this._isSubmit;
            }
            set
            {
                this._isSubmit = value;
            }
        }
        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(RealMoneyAlterSheet));
        }
        
        public static RealMoneyAlterSheet[] FindAll()
        {
            return ((RealMoneyAlterSheet[])(ActiveRecordBase.FindAll(typeof(RealMoneyAlterSheet))));
        }
        
        public static RealMoneyAlterSheet Find(int Id)
        {
            return ((RealMoneyAlterSheet)(ActiveRecordBase.FindByPrimaryKey(typeof(RealMoneyAlterSheet), Id)));
        }
    }
}
