// 
// Generated by ActiveRecord Generator
// 
//
namespace HDSZCheckFlow.Entiy
{
	using Castle.ActiveRecord;
	using Castle.ActiveRecord.Queries;
    
    
    [ActiveRecord("SmallFixedAssetsFlag")]
    public class SmallFixedAssetsFlag : ActiveRecordBase
    {
        
        private string _invSheetId;
        
        private int _isFlag;
        
        [PrimaryKey(PrimaryKeyType.Native)]
        public string InvSheetId
        {
            get
            {
                return this._invSheetId;
            }
            set
            {
                this._invSheetId = value;
            }
        }
        
        [Property()]
        public int IsFlag
        {
            get
            {
                return this._isFlag;
            }
            set
            {
                this._isFlag = value;
            }
        }
        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(SmallFixedAssetsFlag));
        }
        
        public static SmallFixedAssetsFlag[] FindAll()
        {
            return ((SmallFixedAssetsFlag[])(ActiveRecordBase.FindAll(typeof(SmallFixedAssetsFlag))));
        }
        
        public static SmallFixedAssetsFlag Find(string InvSheetId)
        {
            return ((SmallFixedAssetsFlag)(ActiveRecordBase.FindByPrimaryKey(typeof(SmallFixedAssetsFlag), InvSheetId,false)));
        }
    }
}
